#!/bin/sh
set -e

if [ ! -d "/var/lib/mysql/mysql" ]; then
	mysql_install_db --datadir="/var/lib/mysql"

	TEMP_FILE=$(mktemp)
	cat <<-EOF > $TEMP_FILE
	DELETE FROM mysql.user;
	CREATE USER 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
	GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;
	DROP DATABASE IF EXISTS test;
	FLUSH PRIVILEGES;
	EOF

	exec mysqld_safe --init-file=$TEMP_FILE
else
	exec mysqld_safe
fi