#!/bin/sh
set -e

umask 077

MYSQLADMIN='/usr/bin/mysqladmin --defaults-extra-file=/etc/mysql/debian.cnf -u root -p'$MYSQL_ROOT_PASSWORD

trap "$MYSQLADMIN shutdown" 0
trap 'exit 2' 1 2 3 15

if [ ! -d "/var/lib/mysql/mysql" ]; then
	mysql_install_db --datadir="/var/lib/mysql"

	TEMP_FILE=$(gosu mysql mktemp)
	cat <<-EOF > $TEMP_FILE
	DELETE FROM mysql.user;
	CREATE USER 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
	GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;
	DROP DATABASE IF EXISTS test;
	FLUSH PRIVILEGES;
	EOF

	exec mysqld_safe --init-file=$TEMP_FILE & wait
else
	exec mysqld_safe & wait
fi